# Generated by Django 6.0.5 on 2026-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='agendado', max_length=15),
        ),
    ]
