# Generated by Django 6.0.4 on 2026-04-29 17:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="itempedido",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="vendedor",
            name="endereco",
        ),
        migrations.AddField(
            model_name="vendedor",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="avaliacao",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="cpf_cnpj",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendedor",
            name="email",
            field=models.EmailField(
                default="email@exemplo.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="preco_unitario",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vendedor",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="vendedor",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name="itempedido",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pedido",
            table=None,
        ),
        migrations.AlterModelTable(
            name="perfilvendedor",
            table=None,
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.TextField()),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="backend.vendedor",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_pedido",
                to="backend.produto",
            ),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
